// <auto-generated />
using System;
using ColorfulKrakenStudio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColorfulKrakenStudio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328151049_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ColorfulKrakenStudio.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("ColorfulKrakenStudio.Models.Tutorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tutorials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Mamikon",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 45,
                            IsFree = true,
                            IsPublished = true,
                            Plan = "Free",
                            Title = "Feral Tyranid"
                        },
                        new
                        {
                            Id = 2,
                            Author = "David Arroba",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 60,
                            IsFree = false,
                            IsPublished = true,
                            Plan = "Basic",
                            Title = "Imperial Fist"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Kaha Gorska",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 90,
                            IsFree = false,
                            IsPublished = true,
                            Plan = "Pro",
                            Title = "Colorful Wizard"
                        },
                        new
                        {
                            Id = 4,
                            Author = "David Arroba",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 30,
                            IsFree = true,
                            IsPublished = true,
                            Plan = "Free",
                            Title = "Classic Space Marine"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Mamikon",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 75,
                            IsFree = false,
                            IsPublished = true,
                            Plan = "Pro",
                            Title = "Speedpaint Acrylics"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Kaha Gorska",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 120,
                            IsFree = false,
                            IsPublished = true,
                            Plan = "Pro",
                            Title = "Oil Painting Technique"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
