//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorfulKrakenStudio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorfulKrakenStudio.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        internal static string Auth_Error_Invalid {
            get {
                return ResourceManager.GetString("Auth_Error_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked. Try again later..
        /// </summary>
        internal static string Auth_Error_Locked {
            get {
                return ResourceManager.GetString("Auth_Error_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must confirm your email before logging in..
        /// </summary>
        internal static string Auth_Error_NotAllowed {
            get {
                return ResourceManager.GetString("Auth_Error_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Auth_Login_Button {
            get {
                return ResourceManager.GetString("Auth_Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string Auth_Login_NoAccount {
            get {
                return ResourceManager.GetString("Auth_Login_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back.
        /// </summary>
        internal static string Auth_Login_Title {
            get {
                return ResourceManager.GetString("Auth_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string Auth_Register_Button {
            get {
                return ResourceManager.GetString("Auth_Register_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string Auth_Register_HasAccount {
            get {
                return ResourceManager.GetString("Auth_Register_HasAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account.
        /// </summary>
        internal static string Auth_Register_Title {
            get {
                return ResourceManager.GetString("Auth_Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured tutorials.
        /// </summary>
        internal static string Home_Featured {
            get {
                return ResourceManager.GetString("Home_Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse tutorials.
        /// </summary>
        internal static string Home_Hero_Browse {
            get {
                return ResourceManager.GetString("Home_Hero_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for free.
        /// </summary>
        internal static string Home_Hero_SignUp {
            get {
                return ResourceManager.GetString("Home_Hero_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium tutorials created by some of the world&apos;s best painters.
        /// </summary>
        internal static string Home_Hero_Subtitle {
            get {
                return ResourceManager.GetString("Home_Hero_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn to paint miniatures quickly and with great results.
        /// </summary>
        internal static string Home_Hero_Title {
            get {
                return ResourceManager.GetString("Home_Hero_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        internal static string Home_Plans {
            get {
                return ResourceManager.GetString("Home_Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        internal static string Nav_Articles {
            get {
                return ResourceManager.GetString("Nav_Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Nav_Login {
            get {
                return ResourceManager.GetString("Nav_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Nav_Logout {
            get {
                return ResourceManager.GetString("Nav_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        internal static string Nav_MyAccount {
            get {
                return ResourceManager.GetString("Nav_MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        internal static string Nav_Plans {
            get {
                return ResourceManager.GetString("Nav_Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string Nav_SignUp {
            get {
                return ResourceManager.GetString("Nav_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials.
        /// </summary>
        internal static string Nav_Tutorials {
            get {
                return ResourceManager.GetString("Nav_Tutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy now.
        /// </summary>
        internal static string Tutorial_BuyNow {
            get {
                return ResourceManager.GetString("Tutorial_BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string Tutorial_Free {
            get {
                return ResourceManager.GetString("Tutorial_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase to unlock.
        /// </summary>
        internal static string Tutorial_RequiresPlan {
            get {
                return ResourceManager.GetString("Tutorial_RequiresPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Tutorials_Filter_All {
            get {
                return ResourceManager.GetString("Tutorials_Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string Tutorials_Filter_Free {
            get {
                return ResourceManager.GetString("Tutorials_Filter_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string Tutorials_Filter_Paid {
            get {
                return ResourceManager.GetString("Tutorials_Filter_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painting techniques from the world&apos;s best artists.
        /// </summary>
        internal static string Tutorials_Subtitle {
            get {
                return ResourceManager.GetString("Tutorials_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials.
        /// </summary>
        internal static string Tutorials_Title {
            get {
                return ResourceManager.GetString("Tutorials_Title", resourceCulture);
            }
        }
    }
}
